### ISSUE TITLE
blazor web app 菜单异常

### ISSUE THREAD

**Issue by sdly602** [EasyAbp/WeChatManagement#106]
abp 8.3.2 管理菜单中不显示微信管理菜单，直接在浏览器中输入URL后页面显示正常且管理菜单也会出现微信管理，随后点击任何其他菜单后如 设置管理等微信管理菜单会消失，如何修复这个问题。

**Comment by gdlcf88** [comment]
EasyAbp 的模块没有实现 Blazor 模板的支持。
