### ISSUE TITLE
请问UserInfoModel信息如何获取到的

### ISSUE THREAD

**Issue by LFeYls** [EasyAbp/WeChatManagement#11]
请问一下，UserInfoModel中包含的微信用户信息需要通过解密后才能获取到，
但是在WeChatManagement中也没有提供相关的解密接口
那么LoginAppService接口的LoginAsync参数中的UserInfoModel是如何获取到解密后的微信用户信息的呢

**Comment by gdlcf88** [comment]
感谢使用。

对于你的疑问，请参考：
https://github.com/EasyAbp/WeChatManagement/blob/master/docs/MiniPrograms/README.md#%E5%B0%8F%E7%A8%8B%E5%BA%8F%E7%99%BB%E5%BD%95
https://github.com/EasyAbp/WeChatManagement/blob/ff42682a7476f9a1fe52f43a154ba38ebba0792b/modules/MiniPrograms/src/EasyAbp.WeChatManagement.MiniPrograms.Application.Contracts/EasyAbp/WeChatManagement/MiniPrograms/Login/Dtos/LoginInput.cs#L20-L23
