### ISSUE TITLE
小程序登录报错

### ISSUE THREAD

**Issue by slarkerino** [EasyAbp/WeChatManagement#15]
绑定或登录报EasyAbp.Abp.WeChat.Common.Exceptions.SignatureInvalidException:

**Comment by gdlcf88** [comment]
如果是集群式部署，签名需在多个机器之间共享，请安装这个模块：
https://github.com/EasyAbp/Abp.WeChat/tree/master/src/Common/EasyAbp.Abp.WeChat.Common.SharedCache.StackExchangeRedis

并给Setting配置项`EasyAbp.Abp.WeChat.Common.SharedCache.RedisConfiguration`设置一个有效的redis连接字符串

这个方案可以解决开发者在：本地、沙盒环境、线上集群，均使用同一个微信AppId获取签名，而签名无法相互共享，导致互相争抢的问题
