### ISSUE TITLE
"errcode":40163,"errmsg":"code been used...报错

### ISSUE THREAD

**Issue by shangyouming** [EasyAbp/WeChatManagement#16]
在小程序端用wx.login获取的code传入/miniPrograms/login/login后code2SessionResponse方法返回"errcode":40163,"errmsg":"code been used，

**Comment by gdlcf88** [comment]
code**只能使用一次**且有5分钟有效期，请检查用法：https://developers.weixin.qq.com/miniprogram/dev/api/open-api/login/wx.login.html
