### ISSUE TITLE
用Tiered分层解决方案报Cannot resolve parameter Microsoft.AspNetCore.Identity.SignInManager

### ISSUE THREAD

**Issue by shangyouming** [EasyAbp/WeChatManagement#22]
An exception was thrown while activating EasyAbp.WeChatManagement.MiniPrograms.Login.LoginController -> EasyAbp.WeChatManagement.MiniPrograms.Login.LoginAppService.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating EasyAbp.WeChatManagement.MiniPrograms.Login.LoginController -> EasyAbp.WeChatManagement.MiniPrograms.Login.LoginAppService.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Volo.Abp.Autofac.AbpAutofacConstructorFinder' on type 'EasyAbp.WeChatManagement.MiniPrograms.Login.LoginAppService' can be invoked with the available services and parameters:
Cannot resolve parameter 'Microsoft.AspNetCore.Identity.SignInManager`1[Volo.Abp.Identity.IdentityUser] signInManager' of constructor 'Void .ctor(EasyAbp.Abp.WeChat.MiniProgram.Services.Login.LoginService, EasyAbp.Abp.WeChat.MiniProgram.Services.ACode.ACodeService, EasyAbp.Abp.WeChat.MiniProgram.Infrastructure.SignatureChecker, Microsoft.AspNetCore.Identity.SignInManager`1[Volo.Abp.Identity.IdentityUser], Volo.Abp.Data.IDataFilter, Microsoft.Extensions.Configuration.IConfiguration, System.Net.Http.IHttpClientFactory, EasyAbp.WeChatManagement.MiniPrograms.UserInfos.IUserInfoRepository, Volo.Abp.Json.IJsonSerializer, EasyAbp.Abp.WeChat.IWeChatMiniProgramAsyncLocal, EasyAbp.WeChatManagement.MiniPrograms.MiniProgramUsers.IMiniProgramUserRepository, EasyAbp.WeChatManagement.MiniPrograms.IMiniProgramLoginNewUserCreator, EasyAbp.WeChatManagement.MiniPrograms.IMiniProgramLoginProviderProvider, Volo.Abp.Caching.IDistributedCache`1[EasyAbp.WeChatManagement.MiniPrograms.Login.MiniProgramPcLoginAuthorizationCacheItem], Volo.Abp.Caching.IDistributedCache`1[EasyAbp.WeChatManagement.MiniPrograms.Login.MiniProgramPcLoginUserLimitCacheItem], Microsoft.Extensions.Options.IOptions`1[Microsoft.AspNetCore.Identity.IdentityOptions], Volo.Abp.Identity.IdentityUserManager,

**Comment by gdlcf88** [comment]
微信登录功能需确保与Volo.Abp.Identity模块组安装在同应用下才可以工作。
