### ISSUE TITLE
有没有小程序端的示例代码呢

### ISSUE THREAD

**Issue by BeiMeng** [EasyAbp/WeChatManagement#24]
有没有小程序端的示例代码呢

**Comment by BeiMeng** [comment]
小程序登陆授权最佳实践需合适方式

**Comment by blackWins** [comment]
https://github.com/EasyAbp/WeChatManagement/issues/47#issue-1338631595
有解决方案嘛？

**Comment by gdlcf88** [comment]
https://github.com/EasyAbp/WeChatManagement/issues/47#issuecomment-1214721444
