### ISSUE TITLE
引用EasyAbp.Abp.WeChat.Common.SharedCache.StackExchangeRedis 无法使用

### ISSUE THREAD

**Issue by LouieGuo** [EasyAbp/WeChatManagement#26]
我在domain层中使用EasyAbp.Abp.WeChat.Common.SharedCache.StackExchangeRedis，模块也注入了，但没有数据存入到redis中，在appsetting的settings中也配置了redis

**Comment by gdlcf88** [comment]
https://github.com/EasyAbp/WeChatManagement/issues/15#issuecomment-769718739

**Comment by LouieGuo** [comment]
没有效果

**Comment by LouieGuo** [comment]
已经收到您的来信，我会尽快回复。
