### ISSUE TITLE
微信登录失败System.NullReferenceException: 无法获取到 AccessToken

### ISSUE THREAD

**Issue by GotzeWong** [EasyAbp/WeChatManagement#27]
进入Login页面报错
微信 API 返回的内容为：{"errcode":40013,"errmsg":"invalid appid rid:  @60baeab1-5b56bca1-4664e8c5"}'，这是因为什么呢？

![image](https://user-images.githubusercontent.com/7664030/120878622-49729100-c5f0-11eb-8206-79150181ef0b.png)

@gdlcf88 求教下

**Comment by gdlcf88** [comment]
请自行调试，没有人比你更有机会得到真相

**Comment by GotzeWong** [comment]
是我账号的问题，现在已解决，Tks @gdlcf88
