### ISSUE TITLE
你好，与微信API交互和ids请求token的地方是否需要加上异常判断？

### ISSUE THREAD

**Issue by applebananamilk** [EasyAbp/WeChatManagement#29]
由于疏忽导致线上线下的配置不同，本地执行的正常，线上也是一片200，但是执行结果不符合预期。

**Comment by gdlcf88** [comment]
可以为它设计专门的异常处理，你可以尝试pr吗？目前是将ids4原文返回，因此为200。

**Comment by applebananamilk** [comment]
不好意思，我的代码水平较低可能无法提供有效的pr，不过我可以将出现问题的场景重现出来用作参考。

正常的**TokenResponse** 返回中有IsError。可以依据此返回值将异常抛出提示使用者。

正常的返回：
![image](https://user-images.githubusercontent.com/37533208/141417089-7370fbfa-16c3-498c-8101-19925bd0935e.png)

不正常的返回：
![image](https://user-images.githubusercontent.com/37533208/141417164-805d823f-ca22-4cc0-be73-f358e5d3cea4.png)

该数据取自**EasyAbp.WeChatManagement.MiniPrograms.Application** > **LoginAppService** >**RequestIds4LoginAsync**
![image](https://user-images.githubusercontent.com/37533208/141417355-ba3f91fc-1e44-4a51-86b2-d7da4064f0bc.png)

希望有所帮助。

**Comment by gdlcf88** [comment]
请协助确认一下这个问题：失败时，IDS4自身是否已经输出了日志？即我们是否可以不在本地Logger记录远端返回结果呢？

**Comment by applebananamilk** [comment]
测试为开发环境

正常
![@O3QQU`{)E3~CG}YQ4UCSLK](https://user-images.githubusercontent.com/37533208/141475751-26a8cef5-88bf-44c0-af78-1f59bfa0ca77.png)

![D}))01TELNZI%IJ 3XNO~6V](https://user-images.githubusercontent.com/37533208/141475716-51df0353-291d-49f0-ae73-538e65a5afcc.png)

失败
![1UAF7RZE) O1VDYOOY 7NI0](https://user-images.githubusercontent.com/37533208/141475784-e6dd5b83-baca-4133-8457-fdfb984f7ffc.png)

![${S5W%ZK3)D(D~ EOSHH_{3](https://user-images.githubusercontent.com/37533208/141475807-6d52d2f2-3ab9-469d-a213-9660e85302e0.png)

不知道测试姿势是否正确。
结果是成功获取的时候才会输出INF。

触发的条件非常简单，只需要将 [AuthServer:Authority]指向一个不存在的地址就会触发。

**Comment by gdlcf88** [comment]
#30
