### ISSUE TITLE
missing some values when set the permission to user

### ISSUE THREAD

**Issue by davidnasar** [EasyAbp/WeChatManagement#31]
![image](https://user-images.githubusercontent.com/6254752/142732532-2eee17bc-3f98-4e02-a868-98f716f2579f.png)
get the latest packages, there're some values missing when set the permission to user.
can add these two missing values in the Localization

**Comment by gdlcf88** [comment]
Hi, @davidnasar. Welcome to create a PR for it.

**Comment by davidnasar** [comment]
created it already
