### ISSUE TITLE
微信公众号模块

### ISSUE THREAD

**Issue by afresh** [EasyAbp/WeChatManagement#37]
模块命名：`Official` （或者`OfficialAccount`？）。

开发计划：
- [x] 公众号登录页
- [ ] 公众号用户页
- [ ] 发送模板消息

**Comment by gdlcf88** [comment]
实用的模块，Official是合理的命名（与EasyAbp.Abp.WeChat模块中的命名一致）。如果有意实现，请务必注意参考小程序模块的实现，注重统一性、标准化。谢谢！

**Comment by afresh** [comment]
@gdlcf88 好的，我会参照小程序模块去实现。

**Comment by afresh** [comment]
#38 微信公众号模块
