### ISSUE TITLE
实体 UserInfo 不存在

### ISSUE THREAD

**Issue by DreamlessRaw** [EasyAbp/WeChatManagement#40]
当我准备使用UserInfo获取用户信息时，但我得到了实体不存在的错误，确定引用包是没有问题的，因为我可以成功使用微信小程序登录；
我的环境如下
Net Core:6.0
Abp Client:5.1.4
WeChatManagement:1.3.1
下面是我调用的截图实例
![image](https://user-images.githubusercontent.com/47837339/159613566-fd4f8bfb-110a-4e14-85d3-b3e4bfb773a2.png)

**Comment by gdlcf88** [comment]
通过真实存在的实体 ID 进行查询。
