### ISSUE TITLE
Wechat Miniprogram bind user phone number needs to be updated

### ISSUE THREAD

**Issue by slarkerino** [EasyAbp/WeChatManagement#43]
Wechat Bind phone number API should be updated to use new target url, currently it is outdated. 
[See](https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/phonenumber/phonenumber.getPhoneNumber.html)

**Comment by gdlcf88** [comment]
@slarkerino 感谢通知，你可以为它做升级吗？

**Comment by slarkerino** [comment]
@gdlcf88 I have created a PR on abp.wechat repository. Plz check and merge so I can update this repo :P
