### ISSUE TITLE
 Cannot resolve parameter SignInManager

### ISSUE THREAD

**Issue by yufangzhao** [EasyAbp/WeChatManagement#5]
![image](https://user-images.githubusercontent.com/11605512/88007517-ba2bce80-cb40-11ea-9a05-97beffb16a16.png)

Please advise. thanks.

**Comment by gdlcf88** [comment]
How can I reproduce it?

**Comment by yufangzhao** [comment]
just call the login api, and please check the logging file.

**Comment by gdlcf88** [comment]
It works fine in the sample. Please show the whole steps to reproduce your problem, or debug yourself.

**Comment by indexlang** [comment]
what's the reason?
