### ISSUE TITLE
"ActivatorChain": "EasyAbp.WeChatManagement.MiniPrograms.Login.LoginController -> EasyAbp.WeChatManagement.MiniPrograms.Login.LoginAppService"

### ISSUE THREAD

**Issue by indexlang** [EasyAbp/WeChatManagement#51]
与问题 #5 类似错误，删除示例中的modules文件夹，仅保留samples，将samples项目引用改到nuget引用
   <PackageReference Include="EasyAbp.WeChatManagement.MiniPrograms.Application" Version="1.3.4" />
![image](https://user-images.githubusercontent.com/6028356/195053737-291b8668-dae0-4c6b-878e-062c7309d734.png)

**Comment by gdlcf88** [comment]
@indexlang - 你好，请协助试一下 https://github.com/EasyAbp/WeChatManagement/pull/52

**Comment by indexlang** [comment]
我这边是源代码运行没问题，nuget包有问题

**Comment by indexlang** [comment]
下载了个1.3.4的源码运行也没问题，把引用改成nuget包引用后，出现那个错误

**Comment by indexlang** [comment]
不更改的情况下，使用源码没问题，使用nuget包有问题，我的项目abp版本是5.3.3

**Comment by gdlcf88** [comment]
我发布了1.3.5版本应用以上改动，请再帮忙协助尝试，谢谢。

**Comment by indexlang** [comment]
no problem,1.3.5

**Comment by Developer-echo** [comment]
2.1.0 Abp.Wechat Nuget 相同问题

**Comment by gdlcf88** [comment]
> 2.1.0 Abp.Wechat Nuget 相同问题

请创新issue，提供详尽信息。
