### ISSUE TITLE
About custom repositories,MiniProgramRepository,MiniProgramUserRepository,UserInfoRepository.

### ISSUE THREAD

**Issue by rubby1228** [EasyAbp/WeChatManagement#6]
In custom repository files:`MiniProgramRepository,MiniProgramUserRepository,UserInfoRepository`.Use interface `IMiniProgramsDbContext` instead of `MiniProgramsDbContext`. Then I can configure my custom DbContext in abp module replace `MiniProgramsDbContext`.
use case in my `EntityFrameCoreModule`:
`  context.Services.AddAbpDbContext<MemsMiniProgramsDbContext>(options =>
   {
            options.ReplaceDbContext<IMiniProgramsDbContext>();
   });
`

**Comment by gdlcf88** [comment]
Hi @rubby1228, your changes seem to work, but I don't think the `EntityNameDbContext` of an application module should be replaced, ABP framework has another way to customize the existing modules:
https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Extending-Entities#entity-extensions-ef-core

Cloud you please show your usage and business needs?

**Comment by rubby1228** [comment]
> Hi @rubby1228, your changes seem to work, but I don't think the `EntityNameDbContext` of an application module should be replaced, ABP framework has another way to customize the existing modules:
> https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Extending-Entities#entity-extensions-ef-core
> 
> Cloud you please show your usage and business needs?

I use ef core switch DBMS to oracle,My business  is normalized table and field names,so I have to use a custom Dbcontext to rebuild `ConfigureWeChatManagementMiniPrograms`. I want to injection my custom Dbcontext replace MiniProgramsDbContext

**Comment by gdlcf88** [comment]
You are right, I will finish the changes for all our application modules.

**Comment by gdlcf88** [comment]
Moved to https://github.com/EasyAbp/EasyAbpGuide/issues/10

**Comment by rubby1228** [comment]
> You are right, I will finish the changes for all our application modules.

thanks
