### ISSUE TITLE
小程序登陆异常

### ISSUE THREAD

**Issue by baiqiaw** [EasyAbp/WeChatManagement#61]
小程序APP表中有多个相同的APPID，不同租户时，登陆异常

**Comment by gdlcf88** [comment]
你好，我个人商业也有相同场景，没有遇到这个问题。如果无法解决，请你提供异常信息，或自行使用 JetBrains Rider 调试。

**Comment by baiqiaw** [comment]
在WeChatMiniProgramGrantValidator中的WeChatMiniProgramGrantValidator方法中，获取var miniProgram = await _weChatAppRepository.GetMiniProgramAppByAppIdAsync(appId);为空对象或异常，未租户过滤？，如果有多个APPID相同，不同租户的情况时

**Comment by gdlcf88** [comment]
参考：https://docs.abp.io/en/abp/latest/Multi-Tenancy#determining-the-current-tenant

**Comment by baiqiaw** [comment]
我的应用场景是这样的，一个小程序APP中，可以切换租户登陆，所有我重写的您框架的登陆逻辑，允许小程序端在登陆时选择租户进行登陆，这样就会产生同一个APPID，会在不同租户下有一条数据，这时登陆，就会执行我上面描述的，您框架的登陆逻辑验证异常，获取APP对象失败
