### ISSUE TITLE
添加【WeChatManagementMiniProgramsDomainOpenIddictModule】，后使用swagger ui调用接口出现：403

### ISSUE THREAD

**Issue by indexlang** [EasyAbp/WeChatManagement#64]
在domain项目中添加[DependsOn(WeChatManagementMiniProgramsDomainOpenIddictModule)]模块，使用swagger ui调用接口出现：403未授权

**Comment by gdlcf88** [comment]
参考：https://github.com/EasyAbp/WeChatManagement/releases/tag/1.5.0

**Comment by indexlang** [comment]
貌似不是这个原因，我如果不添加[DependsOn(WeChatManagementMiniProgramsDomainOpenIddictModule)]这个，使用swagger账号密码授权没问题，添加上就不能用了

**Comment by indexlang** [comment]
我的示例代码
[测试代码](https://gitee.com/indexlang/weixintest)

**Comment by gdlcf88** [comment]
你的示例代码是私有仓库，请传到github。

**Comment by indexlang** [comment]
已公开

**Comment by indexlang** [comment]
下载[WeChatManagement](https://github.com/EasyAbp/WeChatManagement)源码，运行swagger接口，
https://localhost:44381/swagger/index.html，
使用password授权，获取到的token调用接口返回401
![image](https://user-images.githubusercontent.com/6028356/206883681-81004cab-20a3-42c3-91a9-a03b7ea33f27.png)
![image](https://user-images.githubusercontent.com/6028356/206883728-a6dea623-8b44-44f3-a6e7-788e21325af1.png)

**Comment by gdlcf88** [comment]
你好，这是因为 Scope 不符合 OpenIddict 的规范，请到 docs.abp.io 了解，或参考以上提供的 1.5.0 release 中的提醒。

**Comment by indexlang** [comment]
我找到原因了，EasyAbp.WeChatManagement.MiniPrograms.Domain.OpenIddict  这个库应该安装到AutherServer 项目中，不能安装到domain项目中。

**Comment by indexlang** [comment]
Scope不正确，在哪设置个提醒，这个直接出来token，token不能用不好找原因？

**Comment by gdlcf88** [comment]
> Scope不正确，在哪设置个提醒，这个直接出来token，token不能用不好找原因？

这是 abp 框架的关心范畴，我们无能为力。

**Comment by gdlcf88** [comment]
> 我找到原因了，EasyAbp.WeChatManagement.MiniPrograms.Domain.OpenIddict 这个库应该安装到AutherServer 项目中，不能安装到domain项目中。

实现微信登录，现阶段的设计是要求微信管理模块和 Identity 模块在同一应用中，应该有改造的空间，欢迎研究。
