### ISSUE TITLE
文档地址上的链接无法访问。

### ISSUE THREAD

**Issue by xhanglizhu** [EasyAbp/WeChatManagement#9]
文档地址：https://easyabp.io/modules/WeChatManagement/MiniPrograms/#installation

1.[演示地址](https://wechat.samples.easyabp.io )无法访问。
2.Add DependsOn(typeof(WeChatManagementMiniProgramsXxxModule)) attribute to configure the module dependencies. ([see how](https://github.com/EasyAbp/EasyAbpGuide/blob/master/How-To.md#add-module-dependencies))无法访问。

**Comment by gdlcf88** [comment]
> 1.[演示地址](https://wechat.samples.easyabp.io)无法访问。

演示地址暂未发布，请 @hueifeng 协助发布此演示项目



> ([see how](https://github.com/EasyAbp/EasyAbpGuide/blob/master/How-To.md#add-module-dependencies))无法访问。

此问题将在所有仓库统一解决
