### ISSUE TITLE
显示叹号 是因为啥呢？

### ISSUE THREAD

**Issue by billpeace** [EasyAbp/WeChatManagement#98]
为啥 会显示 叹号呢

![image](https://github.com/EasyAbp/WeChatManagement/assets/372286/da064387-ffaf-4cb2-bfc2-79bc4dc947e1)

**Comment by gdlcf88** [comment]
![image](https://github.com/EasyAbp/WeChatManagement/assets/30018771/1a70a934-960d-44f2-8b91-706376b0fcf8)
未发现问题。
